// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPOVctSRvTT3_ZMirbm4niGrXjc-gAZpY',
    appId: '1:85162150697:web:5a224f565167228c040538',
    messagingSenderId: '85162150697',
    projectId: 'progetto-finale1',
    authDomain: 'progetto-finale1.firebaseapp.com',
    storageBucket: 'progetto-finale1.appspot.com',
    measurementId: 'G-53V2FCXSMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArXsIPy2qxDadlwFrZz5wvrfzA9RNDA-k',
    appId: '1:85162150697:android:368bd7f670040243040538',
    messagingSenderId: '85162150697',
    projectId: 'progetto-finale1',
    storageBucket: 'progetto-finale1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEM-ETNrQPV5N9bzUrV-tPeS4fkMMu8ZE',
    appId: '1:85162150697:ios:9c85e1d6c036a97f040538',
    messagingSenderId: '85162150697',
    projectId: 'progetto-finale1',
    storageBucket: 'progetto-finale1.appspot.com',
    iosBundleId: 'com.example.sushim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEM-ETNrQPV5N9bzUrV-tPeS4fkMMu8ZE',
    appId: '1:85162150697:ios:9c85e1d6c036a97f040538',
    messagingSenderId: '85162150697',
    projectId: 'progetto-finale1',
    storageBucket: 'progetto-finale1.appspot.com',
    iosBundleId: 'com.example.sushim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPOVctSRvTT3_ZMirbm4niGrXjc-gAZpY',
    appId: '1:85162150697:web:c919c9ad18cd34eb040538',
    messagingSenderId: '85162150697',
    projectId: 'progetto-finale1',
    authDomain: 'progetto-finale1.firebaseapp.com',
    storageBucket: 'progetto-finale1.appspot.com',
    measurementId: 'G-8F2C637XFP',
  );
}
